### ISSUE TITLE
Use the same approach for generate swagger scheme

### ISSUE THREAD

**Issue by xgrommx** [fumieval/deriving-aeson#12]
Hello @fumieval

How can we will be use it for generate swagger scheme? I know we can get scheme by aeson options, but how it could be on typelevel?

Maybe need some wrapper like

```
type MyJson = CustomJSON '[...]
type MySwagger = CustomScheme MyJson
```

**Comment by fumieval** [comment]
Hi, you can define something like this (untested):

```
instance (AesonOptions t, Generic a, GToSchema (Rep a), TypeHasSimpleShape a "genericDeclareNamedSchemaUnrestricted") => ToJSON (CustomSwagger t a) where
   declareNamedSchema = genericDeclareNamedSchema $ fromAesonOptions (aesonOptions @t)
```

However, `ToSchema` doesn't seem to be GND-able due to the type roles of [Declare](http://hackage.haskell.org/package/swagger2-2.5/docs/Data-Swagger-Declare.html#t:Declare) so I think you won't be able to use DerivingVia. 

Maybe it helps to have a combinator like `viaCustomSwagger = fmap unCustomSwagger . declareNamedSchema . CustomSwagger`.

**Comment by xgrommx** [comment]
@fumieval probably u have working example?

**Comment by fumieval** [comment]
No I don't. I'm not familiar with swagger either

**Comment by codygman** [comment]
> Hi, you can define something like this (untested):
> 
> ```
> instance (AesonOptions t, Generic a, GToSchema (Rep a), TypeHasSimpleShape a "genericDeclareNamedSchemaUnrestricted") => ToJSON (CustomSwagger t a) where
>    declareNamedSchema = genericDeclareNamedSchema $ fromAesonOptions (aesonOptions @t)
> ```
> 
> However, `ToSchema` doesn't seem to be GND-able due to the type roles of [Declare](http://hackage.haskell.org/package/swagger2-2.5/docs/Data-Swagger-Declare.html#t:Declare) so I think you won't be able to use DerivingVia.
> 
> Maybe it helps to have a combinator like `viaCustomSwagger = fmap unCustomSwagger . declareNamedSchema . CustomSwagger`.

I think we do use deriving via somehow with a private fork of deriving-aeson, I'll have to look into it later today or tomorrow.

**Comment by fumieval** [comment]
Closing as out of scope
