### ISSUE TITLE
Possibility of having a generic CamelTo type

### ISSUE THREAD

**Issue by epicallan** [fumieval/deriving-aeson#8]
Thanks for the library, really nice. 

However, I wanted a `CamelTo` instance where the `Aeson.camelTo2` function took in a period `.` instead of `-` or `_` as currently is the case with `CamelToSnake` and `CamelToKebab` `StringModifier` instances. 

Which brings me to my question, would you be open to a small addition that added a generic `CamelTo` type where the separator is supplied as a type-level string value?

I can submit a PR if you are ok with it

eg
```haskell
instance KnownSymbol separator => StringModifier (CamelTo separator) where
   ...
```

**Comment by fumieval** [comment]
Sounds good to me
